### LOGIN DE USUARIO
POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
  "email": "andres10@ucompensar.edu.co",
  "contrasena": "contraseñaNueva"
}

### REGISTRO DE USUARIO
POST http://localhost:8080/usuarios/create
Content-Type: application/json

{
  "id": 125655612,
  "nombre": "FrankFranklinFranklinFranklinFranklinFranklinFranklinFranklinFranklinFranklinFranklinFranklinFranklinlin",
  "email": "andres10ucompensar.edu.co",
  "telefono": "3204031794",
  "rol": "administrativo"
}

### MODIFICACION DE CONTRASEÑA GENERADA POR LA DESEADA POR EL USUARIO
PATCH http://localhost:8080/usuarios/cambiar-contrasena/125655612
Content-Type: application/json

{
  "contrasenaActual" : "xxx",
  "nuevaContrasena" : "contraseñaNueva"
}

### OBTENER TODOS LOS USUARIOS
GET http://localhost:8080/usuarios/getAll

### OBTENER USUARIO POR ID
GET http://localhost:8080/usuarios/getById/2

### EDICION DE USUARIO
PATCH http://localhost:8080/usuarios/update/125655612
Content-Type: application/json

{
  "contrasena": "xxx"
}

### ELIMINACION DE USUARIO
DELETE http://localhost:8080/usuarios/delete/1
